substitutions:
  _PROJECT_ID: cinetag-distributed-video
  _REGION: us-central1
  _REPOSITORY: cinetag-containers
  _API_SERVICE: cinetag-api
  _WORKER_SERVICE: cinetag-worker
  _FRONTEND_SERVICE: cinetag-frontend
steps:
- name: gcr.io/cloud-builders/docker
  args: ['build','-t','${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/cinetag-api:latest','./backend']
- name: gcr.io/cloud-builders/docker
  args: ['build','-t','${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/cinetag-worker:latest','./backend']
- name: gcr.io/cloud-builders/docker
  args: ['build','-t','${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/cinetag-frontend:latest','./frontend']
- name: gcr.io/cloud-builders/docker
  args: ['push','${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/cinetag-api:latest']
- name: gcr.io/cloud-builders/docker
  args: ['push','${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/cinetag-worker:latest']
- name: gcr.io/cloud-builders/docker
  args: ['push','${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/cinetag-frontend:latest']
