import Link from 'next/link';
import AITagCloud from '@/components/AITagCloud';
import JobStatusBadge from '@/components/JobStatusBadge';
import JobTimeline from '@/components/JobTimeline';
import PublishVideoButton from '@/components/PublishVideoButton';
import RecommendationRail from '@/components/RecommendationRail';
import { safeFetch } from '@/lib/api';
import { DEMO_JOBS, DEMO_VIDEOS, findDemoVideo, gradientForId } from '@/lib/demo-data';
import { formatBitsPerSecond, formatBytes, formatDuration, formatRelativeTime } from '@/lib/format';
import type { JobSummary, VideoSummary } from '@/lib/types';

export const dynamic = 'force-dynamic';

export default async function VideoDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const fromBackend = await safeFetch<VideoSummary | null>(`/api/videos/${encodeURIComponent(id)}`, null);
  const fallback = findDemoVideo(id);
  const video: VideoSummary = (fromBackend && fromBackend.id != null ? fromBackend : fallback) || {
    id,
    title: `Video #${id}`,
    isDemo: true,
  };
  const isDemo = !fromBackend || video.isDemo === true;

  const tags = video.tags && video.tags.length ? video.tags : findDemoVideo(id)?.tags || [];

  // Pull jobs related to this video, fall back to demo.
  const jobs = await safeFetch<JobSummary[]>('/api/jobs', []);
  const relatedJobs = (Array.isArray(jobs) ? jobs : [])
    .filter((j) => String(j.video_id) === String(id))
    .concat(isDemo ? DEMO_JOBS.filter((j) => String(j.video_id) === String(id)) : []);

  const recommendations: VideoSummary[] = DEMO_VIDEOS.filter((v) => String(v.id) !== String(id)).slice(0, 6);

  const grad = video.thumbnailGradient || gradientForId(video.id);
  const tagSummary = tags.slice(0, 6);
  // Prefer the first-class LLM summary, fall back to the older description
  // string, and only then surface placeholder copy. This keeps detail pages
  // accurate when the pipeline has produced a real summary.
  const summaryText =
    video.summary ||
    video.description ||
    (isDemo
      ? 'AI-generated summary will appear here once the LLM tagging stage completes. The demo summary describes pacing, mood, and key visual cues.'
      : 'No AI summary available yet for this video. The summary will be generated by the LLM tagging stage.');

  return (
    <div className="mx-auto max-w-[1400px] space-y-8 px-5 py-8">
      <nav className="text-[12px] text-white/55">
        <Link href="/" className="hover:text-white">Browse</Link>
        <span className="mx-2 text-white/25">/</span>
        <span className="text-white/85">{video.title || `Video #${id}`}</span>
      </nav>

      <section className="panel-strong relative overflow-hidden">
        <div className={`relative aspect-[21/9] w-full ${grad}`}>
          <div className="absolute inset-0 bg-gradient-to-t from-black/85 via-black/30 to-black/30" />
          <div className="absolute right-4 top-4 flex flex-wrap gap-1.5">
            {video.status ? <JobStatusBadge status={String(video.status)} /> : null}
            {video.processingStage ? <JobStatusBadge stage={String(video.processingStage)} /> : null}
            {isDemo ? <span className="chip-neutral">demo</span> : null}
          </div>
          <div className="absolute inset-x-6 bottom-6 flex flex-col gap-3 md:flex-row md:items-end md:justify-between">
            <div className="max-w-3xl">
              <h1 className="text-balance text-3xl font-extrabold tracking-tight md:text-5xl">
                {video.title || `Video #${id}`}
              </h1>
              <div className="mt-2 flex flex-wrap items-center gap-2 text-[12px] text-white/70">
                {video.duration_seconds != null ? <span>{formatDuration(video.duration_seconds)}</span> : null}
                {video.width && video.height ? <span>{video.width}×{video.height}</span> : null}
                {video.codec ? <span className="font-mono">{video.codec}</span> : null}
                {video.bitrate ? <span>{formatBitsPerSecond(video.bitrate / 8)}</span> : null}
                {video.file_size_bytes ? <span>{formatBytes(video.file_size_bytes)}</span> : null}
              </div>
            </div>
            <div className="flex flex-wrap gap-2">
              <Link href="/jobs" className="btn-secondary">View pipeline jobs</Link>
              <Link href="/search" className="btn-primary">Find similar</Link>
            </div>
          </div>
        </div>
      </section>

      <section className="grid grid-cols-1 gap-5 lg:grid-cols-[1fr,360px]">
        <div className="space-y-5">
          <div className="panel-strong p-5">
            <div className="text-[11px] uppercase tracking-wider text-white/50">AI summary</div>
            <p className="mt-2 text-[14px] leading-relaxed text-white/80">{summaryText}</p>
            {tagSummary.length ? (
              <div className="mt-3 flex flex-wrap gap-1.5">
                {tagSummary.map((t, i) => (
                  <span key={`${t.value}-${i}`} className="chip-neutral !text-[11px]">
                    {t.value}
                    {t.confidence != null ? <span className="font-mono text-white/55">·{t.confidence.toFixed(2)}</span> : null}
                  </span>
                ))}
              </div>
            ) : null}
          </div>

          <div className="panel-strong p-5">
            <div className="text-[11px] uppercase tracking-wider text-white/50">AI tags</div>
            <div className="mt-3">
              <AITagCloud tags={tags} />
            </div>
          </div>

          <div className="panel-strong p-5">
            <div className="text-[11px] uppercase tracking-wider text-white/50">Transcript &amp; scenes</div>
            <p className="mt-2 text-[12.5px] text-white/65">
              Transcript and scene-segmentation outputs will appear here when the pipeline completes.
            </p>
            <div className="mt-3 grid grid-cols-1 gap-3 md:grid-cols-2">
              <div className="panel-muted p-3">
                <div className="text-[11px] text-white/55">Transcript snippet</div>
                <p className="mt-1 italic text-[12.5px] text-white/75">
                  &ldquo;{(tags[0]?.value || 'audio').toString()} &mdash; let me show you what comes next…&rdquo;
                </p>
              </div>
              <div className="panel-muted p-3">
                <div className="text-[11px] text-white/55">Detected scene</div>
                <p className="mt-1 text-[12.5px] text-white/75">
                  Scene change at 00:42 — wide establishing shot transitions to handheld close-up.
                </p>
              </div>
            </div>
          </div>

          {relatedJobs.length ? (
            <div className="space-y-3">
              <div className="text-[11px] uppercase tracking-wider text-white/50">Processing job history</div>
              {relatedJobs.map((j) => <JobTimeline key={String(j.id)} job={j} />)}
            </div>
          ) : null}
        </div>

        <aside className="space-y-4">
          <div className="panel p-4">
            <div className="text-[11px] uppercase tracking-wider text-white/50">Asset metadata</div>
            <dl className="mt-2 grid grid-cols-2 gap-2 text-[12px]">
              <Meta k="ID" v={String(video.id)} mono />
              <Meta k="Status" v={String(video.status || 'unknown')} />
              <Meta k="Duration" v={formatDuration(video.duration_seconds)} />
              <Meta k="Resolution" v={video.width && video.height ? `${video.width}x${video.height}` : '—'} />
              <Meta k="Codec" v={video.codec || '—'} mono />
              <Meta k="Bitrate" v={video.bitrate ? formatBitsPerSecond(video.bitrate / 8) : '—'} />
              <Meta k="Frame rate" v={video.frame_rate ? `${video.frame_rate} fps` : '—'} />
              <Meta k="Size" v={formatBytes(video.file_size_bytes)} />
              <Meta k="Uploaded" v={formatRelativeTime(video.created_at)} />
              <Meta k="Confidence" v={video.confidence != null ? video.confidence.toFixed(2) : '—'} mono />
            </dl>
            {video.storage_key ? (
              <div className="mt-3 panel-muted px-3 py-2">
                <div className="text-[10px] uppercase tracking-wider text-white/45">Storage key</div>
                <div className="mt-0.5 truncate font-mono text-[12px] text-white/80">{video.storage_key}</div>
              </div>
            ) : null}
          </div>

          <div className="panel p-4">
            <div className="text-[11px] uppercase tracking-wider text-white/50">Recommendation reason</div>
            <p className="mt-1 text-[12.5px] text-white/75">
              {video.recommendationReason ||
                'Once tagged, CineTag will explain why this asset was recommended based on tag and embedding similarity.'}
            </p>
          </div>

          <div className="panel p-4">
            <div className="text-[11px] uppercase tracking-wider text-white/50">Review status</div>
            <p className="mt-1 text-[12.5px] text-white/75">
              {String(video.status) === 'published'
                ? 'This asset has been reviewed and published to the catalog.'
                : String(video.status) === 'review_ready'
                ? 'This asset has AI tags awaiting human approval.'
                : 'No tags currently pending review.'}
            </p>
            <div className="mt-3 flex flex-wrap items-center gap-2">
              <Link href="/review" className="btn-secondary !text-xs">
                Open review queue
              </Link>
              {!isDemo ? (
                <PublishVideoButton
                  videoId={video.id}
                  initialStatus={String(video.status || '')}
                />
              ) : null}
            </div>
          </div>
        </aside>
      </section>

      <RecommendationRail
        title="Related content"
        reason="Tag overlap and semantic similarity"
        videos={recommendations}
      />
    </div>
  );
}

function Meta({ k, v, mono }: { k: string; v: string; mono?: boolean }) {
  return (
    <div className="panel-muted px-2.5 py-1.5">
      <div className="text-[10px] uppercase tracking-wider text-white/45">{k}</div>
      <div className={`mt-0.5 truncate text-white/90 ${mono ? 'font-mono' : ''}`}>{v}</div>
    </div>
  );
}
