import type {
  JobSummary,
  PlatformMetric,
  ProcessingStage,
  ReviewItem,
  SearchResult,
  VideoSummary,
} from './types';

export const THUMB_GRADIENTS = [
  'bg-thumb-1',
  'bg-thumb-2',
  'bg-thumb-3',
  'bg-thumb-4',
  'bg-thumb-5',
  'bg-thumb-6',
  'bg-thumb-7',
  'bg-thumb-8',
] as const;

const isoMinutesAgo = (m: number) => new Date(Date.now() - m * 60_000).toISOString();

export const DEMO_VIDEOS: VideoSummary[] = [
  {
    id: 'demo-1',
    title: 'Urban Chase Sequence',
    description:
      'High-velocity rooftop pursuit through neon-soaked streets. Heavy practical effects, low-key lighting, kinetic editing.',
    duration_seconds: 4 * 60 + 18,
    status: 'review_ready',
    thumbnailGradient: 'bg-thumb-1',
    tags: [
      { value: 'action', type: 'genre', confidence: 0.94 },
      { value: 'tension', type: 'mood', confidence: 0.88 },
      { value: 'rooftop', type: 'scene', confidence: 0.82 },
      { value: 'car', type: 'object', confidence: 0.91 },
      { value: 'pursuit', type: 'theme', confidence: 0.76 },
    ],
    genres: ['Action', 'Thriller'],
    moods: ['Tense', 'Energetic'],
    confidence: 0.91,
    processingStage: 'review_ready',
    recommendationReason: 'Because you tagged "fast-paced urban thrillers"',
    width: 3840,
    height: 2160,
    codec: 'h264',
    bitrate: 18_500_000,
    frame_rate: 23.976,
    file_size_bytes: 624_000_000,
    created_at: isoMinutesAgo(34),
    storage_key: 'originals/demo-1/urban_chase.mp4',
    isDemo: true,
  },
  {
    id: 'demo-2',
    title: 'Desert Survival Trailer',
    description:
      'Lone traveler crossing dunes at golden hour. Wide-angle drone establishing shots and intimate close-ups.',
    duration_seconds: 2 * 60 + 7,
    status: 'published',
    thumbnailGradient: 'bg-thumb-3',
    tags: [
      { value: 'adventure', type: 'genre', confidence: 0.92 },
      { value: 'survival', type: 'theme', confidence: 0.87 },
      { value: 'desert', type: 'scene', confidence: 0.95 },
      { value: 'reflective', type: 'mood', confidence: 0.71 },
    ],
    genres: ['Adventure', 'Drama'],
    moods: ['Reflective', 'Hopeful'],
    confidence: 0.86,
    processingStage: 'completed',
    recommendationReason: 'Similar mood to "Ocean Documentary Segment"',
    width: 3840,
    height: 1608,
    codec: 'h265',
    bitrate: 22_000_000,
    frame_rate: 24,
    file_size_bytes: 358_000_000,
    created_at: isoMinutesAgo(112),
    storage_key: 'originals/demo-2/desert_survival.mp4',
    isDemo: true,
  },
  {
    id: 'demo-3',
    title: 'Midnight Heist',
    description:
      'A coordinated vault break-in unfolds across split-screen surveillance feeds and synchronized character beats.',
    duration_seconds: 5 * 60 + 42,
    status: 'processing',
    thumbnailGradient: 'bg-thumb-5',
    tags: [
      { value: 'crime', type: 'genre', confidence: 0.93 },
      { value: 'suspense', type: 'mood', confidence: 0.9 },
      { value: 'vault', type: 'object', confidence: 0.79 },
      { value: 'night', type: 'scene', confidence: 0.97 },
    ],
    genres: ['Crime', 'Thriller'],
    moods: ['Suspenseful', 'Cool'],
    confidence: 0.78,
    processingStage: 'llm_tagging',
    recommendationReason: 'Trending in "stylized crime"',
    width: 1920,
    height: 1080,
    codec: 'h264',
    bitrate: 12_000_000,
    frame_rate: 29.97,
    file_size_bytes: 482_000_000,
    created_at: isoMinutesAgo(8),
    storage_key: 'originals/demo-3/midnight_heist.mp4',
    isDemo: true,
  },
  {
    id: 'demo-4',
    title: 'Ocean Documentary Segment',
    description:
      'Pelagic wildlife filmed at depth — bioluminescence, slow-moving predators, ambient hydrophone audio.',
    duration_seconds: 7 * 60 + 30,
    status: 'published',
    thumbnailGradient: 'bg-thumb-4',
    tags: [
      { value: 'documentary', type: 'genre', confidence: 0.96 },
      { value: 'underwater', type: 'scene', confidence: 0.98 },
      { value: 'wildlife', type: 'theme', confidence: 0.93 },
      { value: 'serene', type: 'mood', confidence: 0.82 },
    ],
    genres: ['Documentary', 'Nature'],
    moods: ['Serene', 'Awe'],
    confidence: 0.94,
    processingStage: 'completed',
    recommendationReason: 'Top-rated "calm" content this week',
    width: 3840,
    height: 2160,
    codec: 'h265',
    bitrate: 28_000_000,
    frame_rate: 50,
    file_size_bytes: 1_240_000_000,
    created_at: isoMinutesAgo(420),
    storage_key: 'originals/demo-4/ocean_doc.mp4',
    isDemo: true,
  },
  {
    id: 'demo-5',
    title: 'Sci-Fi Colony Teaser',
    description:
      'A first-look at the colony reveal — towering biodomes, holographic UIs, anamorphic flares, synth score.',
    duration_seconds: 1 * 60 + 48,
    status: 'review_ready',
    thumbnailGradient: 'bg-thumb-7',
    tags: [
      { value: 'sci-fi', type: 'genre', confidence: 0.95 },
      { value: 'futuristic', type: 'theme', confidence: 0.91 },
      { value: 'ominous', type: 'mood', confidence: 0.74 },
      { value: 'spaceport', type: 'scene', confidence: 0.83 },
    ],
    genres: ['Sci-Fi', 'Drama'],
    moods: ['Ominous', 'Curious'],
    confidence: 0.84,
    processingStage: 'review_ready',
    recommendationReason: 'Strong overlap with "Sci-Fi Colony" tag cluster',
    width: 4096,
    height: 1716,
    codec: 'h265',
    bitrate: 24_000_000,
    frame_rate: 24,
    file_size_bytes: 268_000_000,
    created_at: isoMinutesAgo(60),
    storage_key: 'originals/demo-5/scifi_colony.mp4',
    isDemo: true,
  },
  {
    id: 'demo-6',
    title: 'Standup Comedy Clip',
    description:
      'Single-camera black box performance with audience reaction track and well-defined punchline cadence.',
    duration_seconds: 6 * 60 + 12,
    status: 'review_ready',
    thumbnailGradient: 'bg-thumb-6',
    tags: [
      { value: 'comedy', type: 'genre', confidence: 0.97 },
      { value: 'standup', type: 'theme', confidence: 0.95 },
      { value: 'humorous', type: 'mood', confidence: 0.93 },
      { value: 'stage', type: 'scene', confidence: 0.88 },
    ],
    genres: ['Comedy'],
    moods: ['Humorous', 'Light'],
    confidence: 0.93,
    processingStage: 'review_ready',
    recommendationReason: 'Good fit for "lean back" rails',
    width: 1920,
    height: 1080,
    codec: 'h264',
    bitrate: 9_500_000,
    frame_rate: 25,
    file_size_bytes: 192_000_000,
    created_at: isoMinutesAgo(180),
    storage_key: 'originals/demo-6/standup.mp4',
    isDemo: true,
  },
  {
    id: 'demo-7',
    title: 'Nature Macro Reel',
    description:
      'Macro photography compilation — pollinators, droplet impacts, slow-motion bloom sequences.',
    duration_seconds: 3 * 60 + 4,
    status: 'published',
    thumbnailGradient: 'bg-thumb-2',
    tags: [
      { value: 'nature', type: 'genre', confidence: 0.94 },
      { value: 'macro', type: 'scene', confidence: 0.96 },
      { value: 'tranquil', type: 'mood', confidence: 0.86 },
      { value: 'flora', type: 'object', confidence: 0.9 },
    ],
    genres: ['Nature', 'Lifestyle'],
    moods: ['Tranquil', 'Reflective'],
    confidence: 0.9,
    processingStage: 'completed',
    recommendationReason: 'Pairs with "Ocean Documentary Segment"',
    width: 3840,
    height: 2160,
    codec: 'h265',
    bitrate: 32_000_000,
    frame_rate: 60,
    file_size_bytes: 712_000_000,
    created_at: isoMinutesAgo(900),
    storage_key: 'originals/demo-7/nature_macro.mp4',
    isDemo: true,
  },
  {
    id: 'demo-8',
    title: 'Sports Comeback Story',
    description:
      'Underdog athlete arc culminating in a championship moment — multi-camera coverage and crowd ambience.',
    duration_seconds: 8 * 60 + 25,
    status: 'processing',
    thumbnailGradient: 'bg-thumb-8',
    tags: [
      { value: 'sports', type: 'genre', confidence: 0.93 },
      { value: 'inspirational', type: 'mood', confidence: 0.89 },
      { value: 'stadium', type: 'scene', confidence: 0.92 },
      { value: 'comeback', type: 'theme', confidence: 0.84 },
    ],
    genres: ['Sports', 'Documentary'],
    moods: ['Inspirational', 'Energetic'],
    confidence: 0.81,
    processingStage: 'transcription',
    recommendationReason: 'Trending: emotional sports stories',
    width: 1920,
    height: 1080,
    codec: 'h264',
    bitrate: 15_000_000,
    frame_rate: 29.97,
    file_size_bytes: 940_000_000,
    created_at: isoMinutesAgo(2),
    storage_key: 'originals/demo-8/sports_comeback.mp4',
    isDemo: true,
  },
];

export const DEMO_JOBS: JobSummary[] = [
  {
    id: 'job-1011',
    video_id: 'demo-3',
    video_title: 'Midnight Heist',
    status: 'running',
    current_stage: 'llm_tagging',
    retry_count: 0,
    created_at: isoMinutesAgo(8),
    started_at: isoMinutesAgo(7),
    isDemo: true,
  },
  {
    id: 'job-1010',
    video_id: 'demo-8',
    video_title: 'Sports Comeback Story',
    status: 'running',
    current_stage: 'transcription',
    retry_count: 0,
    created_at: isoMinutesAgo(2),
    started_at: isoMinutesAgo(1),
    isDemo: true,
  },
  {
    id: 'job-1009',
    video_id: 'demo-1',
    video_title: 'Urban Chase Sequence',
    status: 'completed',
    current_stage: 'completed',
    retry_count: 0,
    created_at: isoMinutesAgo(34),
    started_at: isoMinutesAgo(33),
    completed_at: isoMinutesAgo(28),
    isDemo: true,
  },
  {
    id: 'job-1008',
    video_id: 'demo-5',
    video_title: 'Sci-Fi Colony Teaser',
    status: 'completed',
    current_stage: 'review_ready',
    retry_count: 1,
    created_at: isoMinutesAgo(60),
    started_at: isoMinutesAgo(58),
    completed_at: isoMinutesAgo(55),
    isDemo: true,
  },
  {
    id: 'job-1007',
    video_id: 'demo-4',
    video_title: 'Ocean Documentary Segment',
    status: 'completed',
    current_stage: 'completed',
    retry_count: 0,
    created_at: isoMinutesAgo(420),
    started_at: isoMinutesAgo(418),
    completed_at: isoMinutesAgo(402),
    isDemo: true,
  },
  {
    id: 'job-1006',
    video_id: 'demo-7',
    video_title: 'Nature Macro Reel',
    status: 'completed',
    current_stage: 'completed',
    retry_count: 0,
    created_at: isoMinutesAgo(900),
    started_at: isoMinutesAgo(898),
    completed_at: isoMinutesAgo(885),
    isDemo: true,
  },
  {
    id: 'job-1005',
    video_id: 'demo-2',
    video_title: 'Desert Survival Trailer',
    status: 'partially_completed',
    current_stage: 'embedding',
    retry_count: 2,
    error_message: 'Embedding stage exceeded retry budget; tags persisted.',
    created_at: isoMinutesAgo(112),
    started_at: isoMinutesAgo(110),
    completed_at: isoMinutesAgo(98),
    isDemo: true,
  },
  {
    id: 'job-1004',
    video_id: 'demo-6',
    video_title: 'Standup Comedy Clip',
    status: 'queued',
    current_stage: 'queued',
    retry_count: 0,
    created_at: isoMinutesAgo(1),
    isDemo: true,
  },
  {
    id: 'job-1003',
    video_id: 'demo-1',
    video_title: 'Frame Sampling Replay',
    status: 'failed',
    current_stage: 'frame_sampling',
    retry_count: 3,
    error_message: 'ffprobe returned non-zero exit code (137).',
    created_at: isoMinutesAgo(180),
    started_at: isoMinutesAgo(179),
    completed_at: isoMinutesAgo(176),
    isDemo: true,
  },
];

export const DEMO_REVIEW_ITEMS: ReviewItem[] = [
  {
    id: 'rv-1',
    video_id: 'demo-3',
    video_title: 'Midnight Heist',
    tag_type: 'mood',
    tag_value: 'suspenseful',
    confidence: 0.92,
    source: 'llm',
    status: 'pending_review',
    rationale:
      'Detected pacing patterns and low-frequency score motifs typical of suspense-driven content.',
    transcript_snippet:
      '“No alarms. Three minutes. Move on my count — three, two, one…”',
    created_at: isoMinutesAgo(7),
    isDemo: true,
  },
  {
    id: 'rv-2',
    video_id: 'demo-3',
    video_title: 'Midnight Heist',
    tag_type: 'object',
    tag_value: 'vault',
    confidence: 0.78,
    source: 'visual_frame',
    status: 'pending_review',
    rationale:
      'Multiple frames feature a circular metal door with a rotary handle — vault-class match.',
    created_at: isoMinutesAgo(6),
    isDemo: true,
  },
  {
    id: 'rv-3',
    video_id: 'demo-1',
    video_title: 'Urban Chase Sequence',
    tag_type: 'theme',
    tag_value: 'pursuit',
    confidence: 0.81,
    source: 'llm',
    status: 'pending_review',
    rationale: 'Continuous chase narrative across rooftop and alley scenes.',
    transcript_snippet: '“Don’t lose him in the alley — cut left at the next gap.”',
    created_at: isoMinutesAgo(28),
    isDemo: true,
  },
  {
    id: 'rv-4',
    video_id: 'demo-5',
    video_title: 'Sci-Fi Colony Teaser',
    tag_type: 'genre',
    tag_value: 'sci-fi',
    confidence: 0.95,
    source: 'llm',
    status: 'pending_review',
    rationale: 'Strong futuristic visual cues and synth-driven score signature.',
    created_at: isoMinutesAgo(55),
    isDemo: true,
  },
  {
    id: 'rv-5',
    video_id: 'demo-5',
    video_title: 'Sci-Fi Colony Teaser',
    tag_type: 'moderation',
    tag_value: 'mild_intensity',
    confidence: 0.62,
    source: 'metadata',
    status: 'pending_review',
    rationale: 'Brief on-screen weapon imagery; recommend human verification.',
    created_at: isoMinutesAgo(50),
    isDemo: true,
  },
  {
    id: 'rv-6',
    video_id: 'demo-6',
    video_title: 'Standup Comedy Clip',
    tag_type: 'mood',
    tag_value: 'humorous',
    confidence: 0.93,
    source: 'transcript',
    status: 'pending_review',
    rationale: 'Audience laughter pattern and joke-cadence signature detected.',
    transcript_snippet: '“So my landlord calls me — and trust me, it gets weirder…”',
    created_at: isoMinutesAgo(170),
    isDemo: true,
  },
];

export const DEMO_SEARCH_RESULTS: SearchResult[] = [
  {
    video_id: 'demo-3',
    title: 'Midnight Heist',
    score: 0.94,
    explanation: 'Matches "suspense", "night", and visual cue "vault".',
    matched_tags: [
      { value: 'suspenseful', type: 'mood' },
      { value: 'night', type: 'scene' },
      { value: 'vault', type: 'object' },
    ],
    thumbnailGradient: 'bg-thumb-5',
    duration_seconds: 5 * 60 + 42,
    genres: ['Crime', 'Thriller'],
    moods: ['Suspenseful'],
    status: 'processing',
    isDemo: true,
  },
  {
    video_id: 'demo-1',
    title: 'Urban Chase Sequence',
    score: 0.88,
    explanation: 'Matches "tense urban action with cars".',
    matched_tags: [
      { value: 'action', type: 'genre' },
      { value: 'tension', type: 'mood' },
      { value: 'car', type: 'object' },
    ],
    thumbnailGradient: 'bg-thumb-1',
    duration_seconds: 4 * 60 + 18,
    genres: ['Action', 'Thriller'],
    moods: ['Tense'],
    status: 'review_ready',
    isDemo: true,
  },
  {
    video_id: 'demo-5',
    title: 'Sci-Fi Colony Teaser',
    score: 0.71,
    explanation: 'Tone-similar but genre-adjacent.',
    matched_tags: [
      { value: 'ominous', type: 'mood' },
      { value: 'futuristic', type: 'theme' },
    ],
    thumbnailGradient: 'bg-thumb-7',
    duration_seconds: 1 * 60 + 48,
    genres: ['Sci-Fi'],
    moods: ['Ominous'],
    status: 'review_ready',
    isDemo: true,
  },
];

export const DEMO_METRICS: PlatformMetric[] = [
  { label: 'Videos Processed', value: '1,284', trend: '+38 today', accent: 'red' },
  { label: 'Jobs Completed (24h)', value: '412', trend: '99.4% success', accent: 'emerald' },
  { label: 'AI Tags Generated', value: '38,904', trend: '+1,621 today', accent: 'violet' },
  { label: 'Searchable Assets', value: '1,177', trend: '92% indexed', accent: 'sky' },
  { label: 'Avg Processing Latency', value: '2m 18s', trend: '−14% wk/wk', accent: 'amber' },
  { label: 'Review Completion Rate', value: '87%', trend: '+5pp wk/wk', accent: 'rose' },
];

export const PIPELINE_STAGES: { key: ProcessingStage | 'queued'; label: string; description: string }[] = [
  { key: 'queued', label: 'Upload', description: 'Direct-to-GCS signed PUT' },
  { key: 'metadata_extraction', label: 'Metadata', description: 'ffprobe streams + container' },
  { key: 'frame_sampling', label: 'Frames', description: 'Periodic + scene-aware sampling' },
  { key: 'scene_segmentation', label: 'Scenes', description: 'Histogram + transformer scenes' },
  { key: 'transcription', label: 'Transcript', description: 'Speech-to-text + diarization' },
  { key: 'llm_tagging', label: 'LLM Tags', description: 'Genres, moods, themes, entities' },
  { key: 'embedding', label: 'Embeddings', description: 'Multi-modal + tag embeddings' },
  { key: 'review_ready', label: 'Review', description: 'Human-in-the-loop QA' },
  { key: 'completed', label: 'Discover', description: 'Search & recommendations' },
];

export const ARCHITECTURE_CARDS = [
  {
    name: 'Cloud Run · API',
    role: 'FastAPI gateway, signed URLs, control plane',
    accent: 'sky' as const,
  },
  {
    name: 'Cloud Run · Worker',
    role: 'Celery pipeline runner, autoscaled by load',
    accent: 'red' as const,
  },
  {
    name: 'Cloud SQL · Postgres',
    role: 'Assets, jobs, tags, embeddings, audit logs',
    accent: 'violet' as const,
  },
  {
    name: 'Memorystore · Redis',
    role: 'Celery broker, result backend, cache',
    accent: 'rose' as const,
  },
  {
    name: 'Google Cloud Storage',
    role: 'Originals, frames, transcripts, thumbnails',
    accent: 'emerald' as const,
  },
  {
    name: 'LLM Tagging Service',
    role: 'Genres, moods, entities, moderation review',
    accent: 'amber' as const,
  },
  {
    name: 'Cloud Monitoring',
    role: 'Metrics, traces, latency SLOs, alerts',
    accent: 'sky' as const,
  },
];

export function findDemoVideo(id: string | number | undefined): VideoSummary | undefined {
  if (!id) return undefined;
  return DEMO_VIDEOS.find((v) => String(v.id) === String(id));
}

export function gradientForId(id: string | number): string {
  const s = String(id);
  let h = 0;
  for (let i = 0; i < s.length; i++) h = (h * 31 + s.charCodeAt(i)) >>> 0;
  return THUMB_GRADIENTS[h % THUMB_GRADIENTS.length];
}

export const SEARCH_EXAMPLES = [
  'find suspenseful night scenes with cars',
  'videos with outdoor adventure and upbeat mood',
  'content similar to sci-fi action trailers',
  'humorous standup with laugh tracks',
  'underwater wildlife with serene mood',
];
